Add `show reboot-cause history` cli
Azure/sonic-utilities pull request #1210
Opened 2020-11-03 09:00 UTC by sujinmkang

- What I did
To make the reboot cause history information available for telemetry service, during processing the reboot-cause on boot, the information is saved in state-db.
The cli command show reboot-cause is changed to support the new file format and file name.
New command show reboot-cause history is added to display the reboot-cause information which is stored in state-db.
- How I did it
Add the 'show reboot-cause history' command to read up to the10 previous reboot-cause information from state-db and display them.
Read the last reboot-cause from the new file "previous-reboot-cause.json" and process the data to display for show reboot-cause

- How to verify it
Unit test added.
Verified also in DUT

- Previous command output (if the output of a command-line utility has changed)

- New command output (if the output of a command-line utility has changed)

admin@sonic:~$ show reboot-cause history
name                 cause        time                          user    comment
-------------------  -----------  ----------------------------  ------  ---------
2020_10_09_04_53_58  warm-reboot  Fri Oct  9 04:51:47 UTC 2020  admin
2020_10_09_02_33_06  reboot       Fri Oct  9 02:29:44 UTC 2020  admin
2020_10_09_02_00_53  fast-reboot  Fri Oct  9 01:58:04 UTC 2020  admin
2020_10_09_01_56_59  reboot       Fri Oct  9 01:53:49 UTC 2020  admin
HLD : Azure/SONiC#669

2020-11-03 17:48 UTC, jleveque requested changes
As comments. Also, since `reboot-cause` is now a group, can you please move this functionality to a new file, `reboot_cause.py` and import the file in main.py? There are a number of other examples.

2020-11-03 17:48 UTC, jleveque commented on show/main.py
> +def readRebootCauseFile():
Rename `read_reboot_cause_file()``

2020-11-04 22:47 UTC, jleveque requested changes

2020-11-04 22:47 UTC, jleveque commented on show/reboot_cause.py
> +    result=""
Add spaces around `=`

2020-11-04 22:47 UTC, jleveque commented on show/reboot_cause.py
> +#
This comment doesn't apply to this function

2020-11-04 22:47 UTC, jleveque commented on show/reboot_cause.py
> +        # Read the last previous reboot cause
Remove the work "last"

2020-11-05 08:43 UTC, lguohan commented
please paste code coverage number.

2020-11-18 01:42 UTC, sujinmkang commented
retest this please!

2020-11-18 23:40 UTC, jleveque requested changes

2020-11-18 23:40 UTC, jleveque commented on show/reboot_cause.py
> +        exit()
Prefer `sys.exit()` to `exit()` (will also need to import sys)

2020-11-19 00:29 UTC, sujinmkang commented
retest this please!

2020-11-19 00:56 UTC, jleveque commented on show/reboot_cause.py
> +        # Read the last previous reboot cause
Still not resolved

2020-11-19 00:57 UTC, jleveque requested changes

2020-11-19 00:57 UTC, jleveque commented on tests/reboot_cause_test.py
> +
Remove this blank line. `mock` and `click` are both thrid-party packages and should be in the same group.

2020-11-19 06:25 UTC, sujinmkang commented on show/reboot_cause.py
> +        # Read the last previous reboot cause
did you mean the comment? :) ok!

2020-11-19 17:43 UTC, sujinmkang commented
retest this please

2020-11-19 19:17 UTC, jleveque requested changes

2020-11-19 19:17 UTC, jleveque commented on show/reboot_cause.py
> +
Remove blank line from EOF

2020-11-19 19:29 UTC, jleveque approved these changes

2020-11-19 19:45 UTC, sujinmkang commented
retest this please

2020-11-20 08:35 UTC, sujinmkang commented
retest this please

2020-11-20 15:50 UTC, lguohan commented
can you fix unit test failure?

2020-11-20 22:35 UTC, sujinmkang commented
@lguohan yes, I'm checking it. I got some other errors on sonic-utilities builds so I'm doing a clean up build to reproduce this unit test failure.

2020-11-25 19:43 UTC, jleveque requested changes

2020-11-25 19:43 UTC, jleveque commented on show/main.py
> +from . import reboot_cause
Please insert this line in alphabetical order

2020-11-25 19:43 UTC, jleveque commented on show/main.py
> +cli.add_command(reboot_cause.reboot_cause)
Please insert this line in alphabetical order

2020-11-28 22:31 UTC, sujinmkang commented
[2020-11-28T07:13:01.701Z] ----------- coverage: platform linux, python 3.7.3-final-0 -----------
[2020-11-28T07:13:01.701Z] Name                                          Stmts   Miss  Cover
[2020-11-28T07:13:01.701Z] -----------------------------------------------------------------
[2020-11-28T07:13:01.702Z] show/reboot_cause.py                             48      4    92%

2020-11-30 18:28 UTC, jleveque approved these changes

2020-12-01 21:58 UTC, merged