[connect][clear] Support --devicename option for connect/clear line ommands
Azure/sonic-utilities pull request #1214
Opened 2020-11-04 07:27 UTC by Blueve

**- What I did**
Support `--devicename` and `-d` option for sonic-clear/connect line commands

**- How I did it**
Add missing options.

**- How to verify it**
Tested on physical SONiC DUT with below initial configuration.
```
admin@sonic:~$ sudo show line -b
  Line    Baud    PID    Start Time    Device
------  ------  -----  ------------  --------
     1    9600      -             -   switch1
```

**- Previous command output (if the output of a command-line utility has changed)**
```
admin@sonic:~$ sudo connect line --devicename switch1
Usage: connect line [OPTIONS] LINENUM
Try "connect line -h" for help.

Error: no such option: --devicename
admin@sonic:~$ sonic-clear line --devicename switch1
Usage: sonic-clear line [OPTIONS] LINENUM
Try "sonic-clear line -h" for help.

Error: no such option: --devicename
```

**- New command output (if the output of a command-line utility has changed)**
```
admin@sonic:~$ sudo connect line --devicename switch1
Successful connection to line 1
Press ^A ^X to disconnect

admin@sonic:~$ sudo sonic-clear line --devicename switch1
admin@sonic:~$ sudo show line -b
  Line    Baud    PID    Start Time    Device
------  ------  -----  ------------  --------
     1    9600      -             -   switch1
```

2020-11-04 18:38 UTC, jleveque approved these changes

2020-11-04 18:49 UTC, lguohan commented
i think we need to add the doc for this command line change.

2020-11-04 18:52 UTC, jleveque requested changes
Please document the new `--devicename` option for both `clear` and `connect` in the CommandReference document.

2020-11-05 04:09 UTC, Blueve commented
@lguohan @jleveque I updated the documents, I found that there are no clear/connect commands documents although we have those commands.
* Add document for show line and move it to console section
* Add document for config console ...
* Add document for connect/clear line

2020-11-05 06:07 UTC, yxieca approved these changes

2020-11-05 08:55 UTC, merged