[unit test][pfcwd] Fix tests that require sudo access
Azure/sonic-utilities pull request #1340
Opened 2020-12-28 17:48 UTC by smaheshm

**- What I did**
The 'config' tests that require sudo access were failing. Fixed it my mocking os.geteuid.

**- How I did it**
Fixed it my mocking os.geteuid.

**- How to verify it**
Unit tests and manual verification

```
before:

samaddik@856d790db1d1:/sonic/src/sonic-utilities/tests$ pytest-3 pfcwd_test.py  -k test_pfcwd_start_actions_masic
>       assert result.exit_code == 0                                                                                                                                                                                                         |
E       AssertionError: assert 1 == 0                                                                                                                                                                                                        |
E        +  where 1 = <Result SystemExit('Root privileges are required for this operation')>.exit_code                                                                                                                                       |
                                                                                                                                                                                                                                             |
pfcwd_test.py:335: AssertionError                                                                                                                                                                                                            |
----------------------------------------------------------------------------------------------------------- Captured stdout setup -----------------------------------------------------------------------------------------------------------|
SETUP                                                                                                                                                                                                                                        |
----------------------------------------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------------------------------------------|
Changed polling interval to 199ms on asic0                                                                                                                                                                                                   |
BIG_RED_SWITCH status is enable on asic0                                                                                                                                                                                                     |
Changed polling interval to 199ms on asic1                                                                                                                                                                                                   |
BIG_RED_SWITCH status is enable on asic1                                                                                                                                                                                                     |
          PORT    ACTION    DETECTION TIME    RESTORATION TIME                                                                                                                                                                               |
--------------  --------  ----------------  ------------------                                                                                                                                                                               |
     Ethernet0      drop               200                 200                                                                                                                                                                               |
     Ethernet4      drop               200                 200                                                                                                                                                                               |
  Ethernet-BP0      drop               200                 200                                                                                                                                                                               |
  Ethernet-BP4      drop               200                 200                                                                                                                                                                               |
Ethernet-BP256      drop               200                 200                                                                                                                                                                               |
Ethernet-BP260      drop               200                 200                                                                                                                                                                               |
                                                                                                                                                                                                                                             |
Root privileges are required for this operation                                                                                                                                                                                              |
                                                                                                                                                                                                                                             |
--------------------------------------------------------------------------------------------------------- Captured stdout teardown ----------------------------------------------------------------------------------------------------------|
TEARDOWN                                                                                                                                                                                                                                     |
================================================================================================== 1 failed, 17 deselected in 0.18 seconds ==================================================================================================|

After:
============================================================================================================ test session starts ============================================================================================================|
platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /sonic/src/sonic-utilities/tests, inifile: pytest.ini
plugins: cov-2.6.0
collected 18 items / 17 deselected                                                                                                                                                                                                          

pfcwd_test.py .                                                                                                                                                                                                                       [100%]

================================================================================================== 1 passed, 17 deselected in 0.22 seconds ==================================================================================================
```
samaddik@856d790db1d1:/sonic/src/sonic-utilities/tests$ pytest-3 pfcwd_test.py  -k test_pfcwd_start_actions_masic                                                                                                                            

**- Previous command output (if the output of a command-line utility has changed)**
 [...]

2020-12-28 19:36 UTC, lguohan submitted a review, later dismissed

2020-12-28 19:39 UTC, jleveque requested changes

2020-12-28 19:39 UTC, jleveque commented on tests/pfcwd_test.py
> +from unittest.mock import patch
`unittest` is part of the standard library. Please move this line to the bottom of the first group of imports, e.g., 

```python
import imp
import os
import sys
from unittest.mock import patch
```

2020-12-28 20:01 UTC, jleveque approved these changes

2020-12-28 20:30 UTC, gechiang approved these changes

2020-12-28 23:00 UTC, smaheshm commented
retest this please

2020-12-29 02:13 UTC, smaheshm commented
retest this please

2020-12-29 17:20 UTC, merged