Refactor code and use mock for testing
Azure/sonic-utilities pull request #1427
Opened 2021-02-11 06:07 UTC by sumukhatv

#### What I did
Refactored code in neighbor_advertiser script and used mock module to unittesting
#### How I did it

#### How to verify it
The neighbor_advertiser test will verify it.
#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)

2021-02-11 08:05 UTC, jleveque requested changes

2021-02-11 08:05 UTC, jleveque commented on tests/neighbor_advertiser_test.py
> +import mock
In Python 3, `mock` is now part of the `unittest` module in the Python standard library. Please use `from unittest import mock` instead.

2021-02-11 18:53 UTC, jleveque approved these changes

2021-02-11 19:21 UTC, prsunny approved these changes

2021-02-19 00:09 UTC, merged

2021-02-19 01:44 UTC, abdosi commented
@sumukhatv please create PR for 201911.

2021-08-30 01:42 UTC, qiluo-msft commented
This commit could not be cleanly cherry-pick to 202012. Please submit another PR.