[201911] platform pre-check for reboot
Azure/sonic-utilities pull request #1472
Opened 2021-03-02 06:46 UTC by santhosh-kt

#### What I did
- Added platform pre check support in reboot script.
- Checking platform based changes before stopping dockers and sonic services.
#### How I did it
On branch reboot_pre_check_201911
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   scripts/reboot

#### How to verify it
- Write a platform pre check script(platform_reboot_pre_check) and place it in /usr/share/sonic/device/\<HWSKU\>/ directory.
- If the script exit with status 0, reboot will be proceeded.
- If script exit with non-zero status, the reboot script gets stopped.

#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)

2021-03-02 18:08 UTC, jleveque requested changes

2021-03-02 18:08 UTC, jleveque commented on scripts/reboot
> +	[[ $? -ne 0 ]] && exit
Please use four spaces to indent, not tabs

2021-03-03 05:14 UTC, jleveque approved these changes

2021-03-04 01:27 UTC, sujinmkang approved these changes

2021-03-11 01:40 UTC, merged