[201811 branch]Stop pmon in reboot
Azure/sonic-utilities pull request #1515
Opened 2021-03-18 04:59 UTC by aravindmani-1

What I did
Stopped PMON before cold boot

How I did it
Edit reboot script and stop pmon docker and services

How to verify it
Check docker ps output just before cold boot is being executed.

Previous command output (if the output of a command-line utility has changed)
New command output (if the output of a command-line utility has changed)
UT:
[cold_boot_UT_201811.txt](https://github.com/Azure/sonic-utilities/files/6161410/cold_boot_UT_201811.txt)

2021-04-12 16:57 UTC, aravindmani-1 commented
@yxieca , @jleveque Can you please review this PR?.

2021-04-12 19:00 UTC, jleveque requested changes
Please also add the same change in the soft-reboot script

2021-04-13 03:35 UTC, aravindmani-1 commented
> Please also add the same change in the soft-reboot script

Added the same change in soft-reboot.

2021-04-15 16:32 UTC, jleveque requested changes

2021-04-15 16:32 UTC, jleveque commented on scripts/soft-reboot
> +exec /sbin/reboot $@
Add newline back at EOF

2021-04-16 01:42 UTC, aravindmani-1 commented on scripts/soft-reboot
> +exec /sbin/reboot $@
Done.

2021-04-16 01:50 UTC, jleveque approved these changes

2021-04-16 01:51 UTC, jleveque commented
/azp run

2021-04-19 16:13 UTC, yxieca approved these changes

2021-04-19 16:14 UTC, merged