[config] Sort Config Db When Saving
Azure/sonic-utilities pull request #1623
Opened 2021-05-18 23:07 UTC by tahmed-dev

#### What I did

Restored cfggen sort method of json data and used it to
sort config db before saving.

closes: https://github.com/Azure/sonic-buildimage/issues/6328 
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

#### How I did it
Restored cfggen sorting method

#### How to verify it
Tested on target

#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)

2021-05-18 23:13 UTC, jleveque requested changes

2021-05-18 23:13 UTC, jleveque commented on config/main.py
> +def sortDict(data):
Python function names should be `snake_case`. I do realize that the function below (`readJsonFile`) isn't following this convention either, but it should for consistency.

2021-05-18 23:34 UTC, jleveque requested changes

2021-05-18 23:34 UTC, jleveque commented on config/main.py
> +    """Sort of data dict"""
Docstring is not very informative. Please add a bit more detail of how it sorts.

2021-05-19 00:49 UTC, jleveque requested changes

2021-05-19 00:49 UTC, jleveque commented on config/main.py
> +    """ Sort of 1st leve and 2nd level dict of data naturally by its key
Typo: s/leve/level

2021-05-19 00:59 UTC, jleveque approved these changes

2021-05-20 16:27 UTC, merged

2021-05-20 16:35 UTC, liat-grozovik commented
@tahmed-dev thanks. Can it be taken to 202012 and 201911 where the issue found ?

2021-05-20 17:12 UTC, tahmed-dev commented
> @tahmed-dev thanks. Can it be taken to 202012 and 201911 where the issue found ?

Thanks @liat-grozovik, Yes, it could be taken to 201911 and 202012 branches.

2021-05-24 23:27 UTC, qiluo-msft commented
202012 cherry-pick is not clean. Please submit another PR on 202012 branch.

2021-05-25 21:29 UTC, dprital commented
@tahmed-dev - please let me know what will be the PR for 202012. Thanks.

2021-05-27 22:42 UTC, yxieca commented
@tahmed-dev Please submit separate PR for 202012 branch. change cannot be cherry-picked cleanly.

2021-05-30 15:46 UTC, dprital commented
@tahmed-dev - What is the PR for 202012 ? Thanks!

2021-06-02 17:44 UTC, tahmed-dev commented
> @tahmed-dev - What is the PR for 202012 ? Thanks!

[PR:1651](https://github.com/Azure/sonic-utilities/pull/1651) port this one to 202012. @dprital I am curious what this PR is blocking? If it blocking test code, I strongly believe the test code has to adapt and we don't need this PR in production.

2021-06-11 22:31 UTC, prsunny commented
@tahmed-dev , is this a bug fix? just curious, why is it required for 201911?

2021-06-11 23:23 UTC, tahmed-dev commented
> @tahmed-dev , is this a bug fix? just curious, why is it required for 201911?

This is no bug here. the unsorted file was an artifact of removing `natsort` from config engine which in turn got removed from 201911 for fast reboot time enhancement.

There is no loss of functionality for master, 202012 or 201911. The issue that was created did not provide details why this is an issue. Removing 201911 label.

2021-06-11 23:28 UTC, prsunny commented
> > @tahmed-dev , is this a bug fix? just curious, why is it required for 201911?
> 
> This is no bug here. the unsorted file was an artifact of removing `natsort` from config engine which in turn got removed from 201911 for fast reboot time enhancement.
> 
> There is no loss of functionality for master, 202012 or 201911. The issue that was created did not provide details why this is an issue. Removing 201911 label.

Thanks Tamer