QOS fieldvalue reference ABNF format to string
Azure/sonic-utilities pull request #1626
Opened 2021-05-20 16:45 UTC by AshokDaparthi

Depends on https://github.com/Azure/sonic-swss/pull/1754

Qos tables in config db and app db used ABNF format i.e "[TABLE_NAME|name] to refer fieldvalue other qos tables.

Example:
Config DB:
"Ethernet92|3": {
"scheduler": "[SCHEDULER|scheduler.1]",
"wred_profile": "[WRED_PROFILE|AZURE_LOSSLESS]"
},
"Ethernet0|0": {
"profile": "[BUFFER_PROFILE|ingress_lossy_profile]"
},
"Ethernet0": {
"dscp_to_tc_map": "[DSCP_TO_TC_MAP|AZURE]",
"pfc_enable": "3,4",
"pfc_to_queue_map": "[MAP_PFC_PRIORITY_TO_QUEUE|AZURE]",
"tc_to_pg_map": "[TC_TO_PRIORITY_GROUP_MAP|AZURE]",
"tc_to_queue_map": "[TC_TO_QUEUE_MAP|AZURE]"
},

AppDB:
"BUFFER_QUEUE_TABLE:Ethernet88:3-4": {
"profile": "[BUFFER_PROFILE_TABLE:egress_lossless_profile]"
},

1#This format is not consistent with other DB schema followed in sonic.
2# Added db_migrator.py case to  change from old format in config_db and appl_db  to new format. 
3#Modified the test case 

Dependent pull requests: 
https://github.com/Azure/sonic-buildimage/pull/7752  - To modify platfrom files 
https://github.com/Azure/sonic-buildimage/pull/7281 - Yang model 
https://github.com/Azure/sonic-swss/pull/1754    - swss change to remove ABNF format

2021-05-21 01:56 UTC, stephenxs requested changes
Hi @AshokDaparthi 
Some other parts need to be updated as well:
- The buffer configuration is stored in APPL_DB. The warm reboot will fail if the switch is upgrading from an image before this change to one after. So db migrator needs to handle APPL_DB as well.
- Suggest adding unit test cases for db migrator.
- The version defined at the beginning of [db_migrator.py](https://github.com/Azure/sonic-utilities/blob/master/scripts/db_migrator.py#L47) needs to be updated as well.
- Existing unit test cases need to be updated accordingly, like [mock_tables](https://github.com/Azure/sonic-utilities/tree/master/tests/mock_tables), and mock tables for [qos](https://github.com/Azure/sonic-utilities/tree/master/tests/qos_config_input), [filter fdb](https://github.com/Azure/sonic-utilities/tree/master/tests/filter_fdb_input), [counter poll](https://github.com/Azure/sonic-utilities/tree/master/tests/counterpoll_input), [SKU create tool](https://github.com/Azure/sonic-utilities/tree/master/tests/sku_create_input), etc... You might want to go over all the test cases.
 I believe the unit test is failing without these changes

Thanks

2021-05-24 22:26 UTC, AshokDaparthi commented
@stephenxs -                                                                                                                                                                                                   Hi Stephan,                                                                                                                                                                                                          I have query regarding "The buffer configuration is stored in APPL_DB. The warm reboot will fail if the switch is upgrading from an image before this change to one after. So db migrator needs to handle APPL_DB as well."                                                                       I have not seen complete warm reboot design. Can you help me to understand, While warm/cold reboot db_migratory.py will trigger config_db update for qos right, which internally trigger swss to update APP_DB with new QOS field values right or during warmreboot swss will not process config_db updates?

2021-05-25 00:56 UTC, stephenxs commented
> @stephenxs - Hi Stephan, I have query regarding "The buffer configuration is stored in APPL_DB. The warm reboot will fail if the switch is upgrading from an image before this change to one after. So db migrator needs to handle APPL_DB as well." I have not seen complete warm reboot design. Can you help me to understand, While warm/cold reboot db_migratory.py will trigger config_db update for qos right, which internally trigger swss to update APP_DB with new QOS field values right or during warmreboot swss will not process config_db updates?

The buffer tables are consumed from APPL_DB instead of CONFIG_DB. 
In a normal starting flow,
- the buffer manager generates table entries and pushes them into APPL_DB. 
- the orchagent consumes the entries in APPL_DB and pushes entries into ASIC_DB.

This is for both dynamic and traditional buffer models.
In a warm reboot flow,
- the `APPL_DB` is saved before warm reboot and restored after it, which means the entries consumed by the orchagent are restored instead of pushed by the manager daemons.
- the buffer manager generates table entries as well, but that's too late for warm reboot to meet its converging time.
- given the data format has been updated before and after warm reboot, we need to update the entries in APPL_DB as well

Hope this helps.

2021-06-01 23:37 UTC, AshokDaparthi commented
/azpw run

2021-07-12 23:40 UTC, AshokDaparthi commented on config/main.py
> +        profile_full_name = "{}".format(override_profile)
Done

2021-07-12 23:40 UTC, AshokDaparthi commented on config/main.py
> +    full_profile_name = '{}'.format(profile)
Done

2021-07-12 23:40 UTC, AshokDaparthi commented on scripts/db_migrator.py
> +    def migrate_qos_db_fieldval_reference_remove(self, table_list=None, db=None, db_num=None, db_delimeter=''):
Done

2021-07-12 23:40 UTC, AshokDaparthi commented on scripts/db_migrator.py
> +                  if field in value:
Done

2021-07-12 23:40 UTC, AshokDaparthi commented on scripts/db_migrator.py
> +                          if "[" not in item or db_delimeter not in item or "]" not in item:
Done

2021-07-12 23:41 UTC, AshokDaparthi commented on scripts/db_migrator.py
> +        self.migrate_qos_fieldval_reference_format()
When i am doing it 2_0_2 is new one, i added new version 2_0_3

2021-07-30 06:40 UTC, stephenxs approved these changes

2021-08-31 17:16 UTC, AshokDaparthi commented
/azpw run

2021-08-31 17:16 UTC, mssonicbld commented
/AzurePipelines run

2021-08-31 23:53 UTC, AshokDaparthi commented
@stephenxs , @neethajohn - Could you please re approve.                                                                                                                                  Plan is to 
1# Merge sonic-utilities 
2# Modify SHA                                                                                                                                                                                                   3# Then re trigger sonic-swss Checks and merge it                                                                                                                                     4# Merge sonic-buildimage

2021-09-01 04:42 UTC, AshokDaparthi commented
> 
> 
> > @stephenxs , @neethajohn - Could you please re approve. Plan is to
> > 1# Merge sonic-utilities
> > 2# Modify SHA 3# Then re trigger sonic-swss Checks and merge it 4# Merge sonic-buildimage
> 
> Hi @AshokDaparthi
> Two questions.
> 
>     1. What's the difference between this one and the commit we approved? Is it just rebased to the latest master commit?
> 
>     2. To what branch will this feature be merged?
>        I was wondering whether we will have a dedicated sonic-mgmt branch for testing sonic switch without this feature. Check [this PR](https://github.com/Azure/sonic-mgmt/pull/3824#issuecomment-906797660) for details
>        @neethajohn FYI.
> 
> 
> Thanks



> 
> 
> > @stephenxs , @neethajohn - Could you please re approve. Plan is to
> > 1# Merge sonic-utilities
> > 2# Modify SHA 3# Then re trigger sonic-swss Checks and merge it 4# Merge sonic-buildimage
> 
> Hi @AshokDaparthi
> Two questions.
> 
>     1. What's the difference between this one and the commit we approved? Is it just rebased to the latest master commit?
> 
>     2. To what branch will this feature be merged?
>        I was wondering whether we will have a dedicated sonic-mgmt branch for testing sonic switch without this feature. Check [this PR](https://github.com/Azure/sonic-mgmt/pull/3824#issuecomment-906797660) for details
>        @neethajohn FYI.
> 
> 
> Thanks

1# No changes, I did rebase all my pull requests to latest master 
2# Yes, We required sonic-mgmt branch separation before and after merge this changes.

2021-09-01 05:41 UTC, stephenxs approved these changes

2021-09-01 20:59 UTC, AshokDaparthi commented
@neethajohn - Could you please review and approve.

2021-09-02 17:20 UTC, lguohan approved these changes

2021-09-02 17:20 UTC, zhangyanzhao commented
@neethajohn  can you please help to review and approve this.

2021-09-02 17:21 UTC, merged