Change to use rvtysh when calling the show commands (#1572)
Azure/sonic-utilities pull request #1647
Opened 2021-05-31 07:41 UTC by xumia

Change to use rvtysh when calling the show commands

#### What I did
Change to use rvtysh when calling the show commands
Merge code from master and fix code conflict, see #1572

#### How I did it

#### How to verify it

#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)

2021-05-31 08:53 UTC, qiluo-msft approved these changes

2021-05-31 09:47 UTC, qiluo-msft requested changes
We don't have `rvtysh` command on 201911 branch

2021-05-31 10:34 UTC, xumia commented
> We don't have `rvtysh` command on 201911 branch

We have merged the command 'vtysh' to 201911 branch, see https://github.com/Azure/sonic-buildimage/pull/7572

2021-06-28 03:41 UTC, qiluo-msft approved these changes

2021-06-30 01:18 UTC, merged