[debug dump util] Match Infrastructure
Azure/sonic-utilities pull request #1666
Opened 2021-06-11 18:44 UTC by vivekreddynv

DEBUG DUMP UTIL PR ORDER: 1

#### What I did

HLD for Dump Utility: [HLD](https://github.com/Azure/SONiC/pull/789).
* Added the Logic for Match Infrastructure along with corresponding unit tests. 

For More Info on MatchRequest and MatchEngine, Check this section in the HLD:
[MatchInfra](https://github.com/Azure/SONiC/blob/fda816c24570df33f253e525bb3fee7ae72fa431/doc/Dump-Utility.md#24-Match-Infrastructure)

#### How I did it

#### How to verify it

```
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_bad_key_pattern PASSED [ 82%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_bad_request PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_invalid_combination PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_invalid_db PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_just_keys_return_fields_compat PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_no_file PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_no_source PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_no_table PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_no_value PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_return_fields_bad_format PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_vague_source PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchRequestValidation::test_valid_match_request PASSED [ 83%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_field_value_match PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_field_value_match_list_type PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_field_value_no_match PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_file_source PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_file_source_with_key_ptrn PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_file_source_with_not_only_return_keys PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_for_no_key_match PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_for_no_match PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_just_keys_false PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_key_pattern_complex PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_key_pattern_wildcard PASSED [ 84%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_match_entire_list PASSED [ 85%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_return_fields_with_all_filtering PASSED [ 85%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_return_fields_with_field_value_filtering PASSED [ 85%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_return_fields_with_key_filtering PASSED [ 85%]
tests/dump_tests/match_engine_test.py::TestMatchEngine::test_return_keys PASSED [ 85%]
```

#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)

2021-06-22 22:00 UTC, SuvarnaMeenakshi requested changes
Please added unit test for namespace DBs as well.

2021-06-22 22:57 UTC, vivekreddynv commented
> Please added unit test for namespace DBs as well.

I've added those tests in the top level CLI.
```
tests/dump_tests/dump_state_test.py::TestDumpStateMultiAsic::test_default_namespace PASSED [ 82%]
tests/dump_tests/dump_state_test.py::TestDumpStateMultiAsic::test_namespace_asic0 PASSED [ 82%]
tests/dump_tests/dump_state_test.py::TestDumpStateMultiAsic::test_namespace_asic1 PASSED [ 82%]
tests/dump_tests/dump_state_test.py::TestDumpStateMultiAsic::test_invalid_namespace PASSED [ 82%]
```
[https://github.com/Azure/sonic-utilities/blob/4c3b775b03e090a2e0c0cb60b283c3ea143d88fc/tests/dump_tests/dump_state_test.py#L184](https://github.com/Azure/sonic-utilities/blob/4c3b775b03e090a2e0c0cb60b283c3ea143d88fc/tests/dump_tests/dump_state_test.py#L184)

2021-06-23 00:47 UTC, vivekreddynv commented on dump/match_infra.py
> +
Check added

2021-06-23 00:58 UTC, vivekreddynv commented on tests/dump_tests/match_engine_test.py
> +    def test_bad_key_pattern(self):
Yeah, there is. For MatchEngine tests i'm using the data in the mock_tables/ folder

2021-06-23 15:35 UTC, vivekreddynv commented on dump/match_infra.py
> +    "FILE_R_EXEP": "Exception Caught While Reading the json cfg file provided"
Added

2021-06-24 15:04 UTC, SuvarnaMeenakshi commented on tests/dump_tests/match_engine_test.py
> +    def test_bad_key_pattern(self):
Got it, the existing mock_tables is getting used.

2021-06-29 20:16 UTC, liat-grozovik commented
@SuvarnaMeenakshi could you please review following unit test added?

2021-07-07 07:49 UTC, SuvarnaMeenakshi approved these changes
LGTM

2021-07-07 08:20 UTC, liat-grozovik approved these changes

2021-07-14 20:01 UTC, merged

2021-07-20 18:51 UTC, vivekreddynv commented
Request for 202106