Add an option in queue stat to display voq counters.
Azure/sonic-utilities pull request #1827
Opened 2021-09-17 22:14 UTC by skbarista

#### What I did

#### How I did it

#### How to verify it

#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)

2021-11-01 19:42 UTC, abdosi requested changes
Please add UT for this

2021-11-01 19:43 UTC, abdosi commented
also please add some description in PR Header

2022-05-24 05:23 UTC, rlhui commented
@abdosi - reminder to re-review this PR. Thanks.

2022-06-21 04:19 UTC, abdosi approved these changes

2022-06-21 04:20 UTC, merged