Add trap flow counter support
Azure/sonic-utilities pull request #1868
Opened 2021-10-11 07:40 UTC by Junchao-Mellanox

#### What I did

Add trap flow counter CLI support. See HLD: https://github.com/Azure/SONiC/pull/858

#### How I did it

Add new command:

- counterpoll flowcnt-trap enable/disable
- counterpoll flowcnt-trap interval
- show flowcnt-trap stats
- sonic-clear flowcnt-trap
- Extend command: counterpoll show

#### How to verify it

Unit test/Manual test

#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)

2021-10-12 02:52 UTC, Junchao-Mellanox commented
Hi @qiluo-msft , could you please suggest a reviewer from MSFT side? Thanks!

2021-11-03 01:52 UTC, Junchao-Mellanox commented
/azpw run

2021-11-03 01:52 UTC, mssonicbld commented
/AzurePipelines run

2021-11-15 07:52 UTC, Junchao-Mellanox commented
/azpw run

2021-11-15 07:52 UTC, mssonicbld commented
/AzurePipelines run

2021-11-22 07:55 UTC, Junchao-Mellanox commented
/azpw run Azure.sonic-utilities

2021-11-22 07:55 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-utilities

2021-11-23 00:38 UTC, prsunny commented
@dgsudharsan, can you review this as well?

2021-11-23 02:43 UTC, dgsudharsan requested changes

2021-11-23 02:43 UTC, dgsudharsan commented on scripts/flow_counters_stat
> +                    # Counter OID not equal means the trap was removed and added again. Removing a trap would cause
This is a good logic to handle. However, what if OID returned is the same as before delete? Should we rather not check if the diff is negative and consider it as a case where trap got deleted?

2021-11-23 12:00 UTC, Junchao-Mellanox commented
/azpw run Azure.sonic-utilities

2021-11-23 12:00 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-utilities

2021-11-23 23:01 UTC, Junchao-Mellanox commented
/azpw run Azure.sonic-utilities

2021-11-23 23:01 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-utilities

2021-11-24 01:34 UTC, dgsudharsan approved these changes

2021-11-24 01:38 UTC, keboliu approved these changes

2021-11-25 00:31 UTC, prsunny approved these changes

2021-11-25 00:32 UTC, merged